# Generated by Django 6.0.5 on 2026-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='category',
            field=models.CharField(choices=[('hot', 'Cafes Calientes'), ('cold', 'Cafes Frios'), ('desserts', 'Postres'), ('sandwiches', 'Sandwiches'), ('promotions', 'Promociones')], default='hot', max_length=20),
        ),
    ]
