# Generated by Django 6.0.5 on 2026-06-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcafe', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('shipped', 'Enviado')], default='pending', max_length=20),
        ),
    ]
